[[license]]
name = "ICU"
licence = "Unicode-3.0"
homepage = "https://icu.unicode.org"
file = "icu.txt"

[[license]]
name = "imagecodecs"
licence = "BSD-3-Clause"
homepage = "https://www.cgohlke.com"
file = "imagecodecs.txt"

[[license]]
name = "numpy"
licence = "BSD-3-Clause AND 0BSD AND MIT AND Zlib AND CC0-1.0"
homepage = "https://numpy.org"
file = "numpy.txt"

[[license]]
name = "pillow"
licence = "MIT-CMU"
homepage = "https://python-pillow.github.io"
file = "pillow.txt"

[[license]]
name = "PySide6"
licence = "LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only"
homepage = "https://pyside.org"
file = "pyside6.txt"

[[license]]
name = "Python"
licence = "PSF-2.0"
homepage = "https://www.python.org"
file = "python.txt"

[[license]]
name = "Qt"
licence = "LGPL-3.0-only"
homepage = "https://www.qt.io"
file = "qt.txt"

[[license]]
name = "shiboken6"
licence = "LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only"
homepage = "https://pyside.org"
file = "shiboken6.txt"

[[license]]
name = "texture-courier"
licence = "MIT"
homepage = "https://github.com/furudean/texture-courier"
file = "texture-courier.txt"

[[license]]
name = "Zstandard"
licence = "BSD-3-Clause"
homepage = "https://facebook.github.io/zstd/"
file = "zstd.txt"
